name: PR Verify Builds

on:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [Windows-latest, Ubuntu-latest, macOS-latest]
        configuration: [Debug, Release]
        include:
          - os: windows-latest
            cmake-parameters: -G "Visual Studio 16 2019" -A Win32
          - os: ubuntu-latest
            cmake-parameters: -G "Unix Makefiles"
          - os: macos-latest
            cmake-parameters: -G "Xcode"
    steps:
      - uses: actions/checkout@v2
      - name: Generate cmake files
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.cmake-parameters }}
      - name: Build
        run: cmake --build build/ --config ${{ matrix.configuration }}
